### PR TITLE
Rhmap 4127.offline.detection

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by corinnekrych** [comment]
@danielpassos do mind to review?

**Comment by danielpassos** [comment]
:eyes:

**Comment by danielpassos** [comment]
Hi @corinnekrych I did some test using [helloworld-ios-swift](https://github.com/feedhenry-templates/helloworld-ios-swift) and it did not work was we expected. Here is what I did

1. Open the app
1. Wait for init callback
1. Turn off wifi
1. Fire the call request
1. Wait a bit
1. Turn on the wifi 

I did not received a server response when internet got back

**Comment by corinnekrych** [comment]
@danielpassos I've simplified the implementation. I also slightly changed helloworld https://github.com/feedhenry-templates/helloworld-ios-swift/pull/2 to make it easier to test.
I run the test you described successfully.
could you have a second look please?

**Comment by danielpassos** [comment]
* Open the app
* Wait for init callback

```
initialized OK
Reachable via WiFi or Cell
```

* Turn off wifi
* Fire the call request
* Wait a bit

```
Not reachable
Cloud Call Failed, Error Domain=FHHttpClient Code=1 "Offline mode" UserInfo={NSLocalizedDescription=Offline mode, error=offline}
Cloud Call Failed, Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSErrorFailingURLStringKey=http://testing-vg5l5darnawifaqcoifu7lkt-dev.passos.skunkhenry.com/hello, _kCFStreamErrorCodeKey=8, NSErrorFailingURLKey=http://testing-vg5l5darnawifaqcoifu7lkt-dev.passos.skunkhenry.com/hello, NSLocalizedDescription=The Internet connection appears to be offline., _kCFStreamErrorDomainKey=12, NSUnderlyingError=0x15da2780 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8}}}
```

* Turn on the wifi 

```
Reachable via WiFi or Cell
```

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
