### PR TITLE
FH-2580 travis-ci support

### PR DESCRIPTION
**Pull request by famer**
Enabling support of travis-ci for master branch.
Runs unit tests only, at this moment.

### CODE REVIEW

**Comment by famer** [comment]
@corinnekrych please, take a look.

**Comment by danielpassos** [comment]
@corinnekrych @famer Just enable @travis-ci to this repo

**Comment by corinnekrych** [comment]
+1
ready to be rebased and merged

**Comment by famer** [comment]
Rebased.

**Comment by corinnekrych** [comment]
@famer Merged thanks!

**Pull request merged**
