### PR TITLE
FH-2619 code coverage via coveralls.io

### PR DESCRIPTION
**Pull request by famer**

### CODE REVIEW

**Comment by famer** [comment]
https://coveralls.io/github/famer/fh-ios-swift-sdk

**Comment by corinnekrych** [comment]
@famer I think there is something fishy: 
- the coverage report you get: https://coveralls.io/builds/5612231 only takes as source file file from Pods ie: dependencies file. 
- In the fh-ios-sk coverage report: https://coveralls.io/builds/5612231I get coverage only for the actual source files not the pods.
:eyes:

**Comment by corinnekrych** [comment]
@famer if i run locally the coverage in Xcode i get 72% coverage
https://www.dropbox.com/s/ni8z50klqygi9um/Screenshot%202016-04-01%2010.31.46.png?dl=0

**Comment by famer** [comment]
@corinnekrych I see, I'll investigate it.

**Comment by corinnekrych** [comment]
@famer Timur: i think this is the PR we need to exclude Pods https://github.com/SlatherOrg/slather/pull/147 it's worth taking a look.

**Comment by corinnekrych** [comment]
@famer I'm closing this one for the moment. we'll r visit it later.

**Pull request closed without merging**
